on:
  workflow_dispatch:
    inputs:
      tags:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          pwd && cd CookieKatz-BOF && nmake all && dir /s
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CookieKatz-BOF/cookie-katz.cna
            CookieKatz-BOF/x64/Release/FindChromeProcess.x64.o
            CookieKatz-BOF/x64/Release/CookieKatzBOF.x64.o
