on:
  workflow_dispatch:
    inputs:
      tags:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          mkdir release
          cd CookieKatz-BOF && nmake all
          cd .. 
          mv x64\Release\* release\
          cd CredentialKatz-BOF && nmake all
          cd .. 
          mv x64\Release\* release\
      - name: ZipIt
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: '@zip.lst'
          filename: 'ChromeKatzBOFs.zip'
          command: 'echo ./chrome-katz.cna >> zip.lst && echo ./release/ >> zip.lst'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ChromeKatzBOFs.zip
