on:
  workflow_dispatch:
    inputs:
      tags:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          cd CookieKatz-BOF && nmake all
      - name: ZipIt
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: 'CookieKatz_Release'
          filename: 'CookieKatzBOF.zip'
          command: 'mkdir CookieKatz_Release && cp -r x64 CookieKatz_Release/ && cp CookieKatz-BOF/cookie-katz.cna CookieKatz_Release/'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CookieKatzBOF.zip
