on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build
        run: |
          cd CookieKatz-BOF && nmake all
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cookie-katz.cna
            CookieKatzBOF.x64.o
            FindChromeProcess.x64.o
